version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
      - "1883:1883"
    networks:
      rede:
        ipv4_address: 10.5.0.5
    volumes:
      - /mnt/c/Users/geral/Documents/PlatformIO/Projects/telegestao-firmware/nodered-data/data:/data
networks:
  rede:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1